version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - gem install berkshelf -v 5.1.0
      - gem install mixlib-archive -v 0.4.4
  build:
    commands:
      - echo Entered the build phase...
      - export REVISION_ID=`echo $REVISION | sed 's/\//-/g'`
      - berks package mh-opsworks-recipes-${REVISION_ID}.tar.gz
artifacts:
  files:
    - mh-opsworks-recipes-${REVISION_ID}.tar.gz
  discard-paths: yes

