name             'mh-opsworks-berkshelf'
maintainer       'Dan Collis-Puro'
maintainer_email 'dan@collispuro.net'
license          'All rights reserved'
description      'Installs/Configures mh-opsworks-berkshelf'
long_description 'Installs/Configures mh-opsworks-berkshelf'
version          '0.1.0'
