name             'mh-opsworks-recipes'
maintainer       'Dan Collis-Puro'
maintainer_email 'dan@collispuro.net'
license          'All rights reserved'
description      'Installs/Configures mh-opsworks-recipes'
long_description 'Installs/Configures mh-opsworks-recipes'
version          '0.1.0'

depends 'nfs', '~> 2.1.0'
depends 'apt'
